---
title: "Logistic Regression: Detecting Cyber Attacks in Water Networks"
output: html_notebook
---

```{r}
# Remove all variables from the R environment to create a fresh start
rm(list=ls())

# Load datasets
train1 <- read.csv("train_dataset01.csv")
train2 <- read.csv("train_dataset02.csv")
test <- read.csv("test_dataset.csv")

# Remove variables that don't vary
ignore = c("LEVEL_T5", "FLOW_PU3", "FLOW_PU5", "FLOW_PU9", "STATUS_PU3", "STATUS_PU5", "STATUS_PU8", "STATUS_PU9")
train2.small <- train2[, -which(names(train2) %in% ignore)]
```


Utilising the dataset with ATT_FLAG set as True and False (train2), logistic regression can be performed.
```{r}
library(caTools)
set.seed(100)
spl <-sample.split(train2.small$ATT_FLAG, SplitRatio =0.7)
attackTrain <- subset(train2.small, spl == TRUE)
attackTest <- subset(train2.small, spl == FALSE)
```

```{r}
attackTrain$DATETIME <- NULL

model1 <- glm(ATT_FLAG~., data = attackTrain, family = binomial)
summary(model1)
predict1 <- predict(model1, newdata = attackTest, type = 'response')
table1 <- table(predict1 >= 0.5, attackTest$ATT_FLAG)

precision <- table1[2,2]/sum(table1[2,])
recall <- table1[2,2]/sum(table1[,2])
f1 <- 2 * precision * recall / (precision + recall)

precision
recall
f1
```


```{r}
# read batadal data
batadal <- read.csv("batadal_train.csv")

# try on test set
predict2 <- predict(model1, newdata = batadal, type = 'response')
table2 <- table(predict2 >= 0.5, batadal$ATT_FLAG)

precision <- table2[2,2]/sum(table1[2,])
recall <- table2[2,2]/sum(table1[,2])
f1 <- 2 * precision * recall / (precision + recall)

precision
recall
f1
```

